-- MySQL Script generated by MySQL Workbench
-- Fri May 27 13:40:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LocationDeFilm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LocationDeFilm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LocationDeFilm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `LocationDeFilm` ;

-- -----------------------------------------------------
-- Table `LocationDeFilm`.`CategoriesDeFilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocationDeFilm`.`CategoriesDeFilms` (
  `CodeCategoriesDeFilms` INT NOT NULL AUTO_INCREMENT,
  `Nom_Categorie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodeCategoriesDeFilms`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LocationDeFilm`.`ListeDesFilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocationDeFilm`.`ListeDesFilms` (
  `codeListesDesFilms` INT NOT NULL AUTO_INCREMENT,
  `Titres` VARCHAR(45) NOT NULL,
  `DateDeSortie` DATETIME NOT NULL,
  `CategoriesDeFilms_CodeCategoriesDeFilms` INT NOT NULL,
  PRIMARY KEY (`codeListesDesFilms`, `CategoriesDeFilms_CodeCategoriesDeFilms`),
  INDEX `fk_ListeDesFilms_CategoriesDeFilms1_idx` (`CategoriesDeFilms_CodeCategoriesDeFilms` ASC) VISIBLE,
  CONSTRAINT `fk_ListeDesFilms_CategoriesDeFilms1`
    FOREIGN KEY (`CategoriesDeFilms_CodeCategoriesDeFilms`)
    REFERENCES `LocationDeFilm`.`CategoriesDeFilms` (`CodeCategoriesDeFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LocationDeFilm`.`ListeClients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocationDeFilm`.`ListeClients` (
  `CodeClients` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(25) NOT NULL,
  `Prenom` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ListeDesFilms_codeListesDesFilms` INT NOT NULL,
  PRIMARY KEY (`CodeClients`, `ListeDesFilms_codeListesDesFilms`),
  INDEX `fk_ListeClients_ListeDesFilms_idx` (`ListeDesFilms_codeListesDesFilms` ASC) VISIBLE,
  CONSTRAINT `fk_ListeClients_ListeDesFilms`
    FOREIGN KEY (`ListeDesFilms_codeListesDesFilms`)
    REFERENCES `LocationDeFilm`.`ListeDesFilms` (`codeListesDesFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LocationDeFilm`.`FilmsLoues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocationDeFilm`.`FilmsLoues` (
  `CodeLocation` INT NOT NULL AUTO_INCREMENT,
  `DateDeLocation` DATE NOT NULL,
  `DateDeRetour` DATE NOT NULL,
  `ListeClients_CodeClients` INT NOT NULL,
  `ListeClients_ListeDesFilms_codeListesDesFilms` INT NOT NULL,
  `ListeDesFilms_codeListesDesFilms` INT NOT NULL,
  PRIMARY KEY (`CodeLocation`),
  INDEX `fk_FilmsLoues_ListeClients1_idx` (`ListeClients_CodeClients` ASC, `ListeClients_ListeDesFilms_codeListesDesFilms` ASC) VISIBLE,
  INDEX `fk_FilmsLoues_ListeDesFilms1_idx` (`ListeDesFilms_codeListesDesFilms` ASC) VISIBLE,
  CONSTRAINT `fk_FilmsLoues_ListeClients1`
    FOREIGN KEY (`ListeClients_CodeClients` , `ListeClients_ListeDesFilms_codeListesDesFilms`)
    REFERENCES `LocationDeFilm`.`ListeClients` (`CodeClients` , `ListeDesFilms_codeListesDesFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FilmsLoues_ListeDesFilms1`
    FOREIGN KEY (`ListeDesFilms_codeListesDesFilms`)
    REFERENCES `LocationDeFilm`.`ListeDesFilms` (`codeListesDesFilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LocationDeFilm`.`ConservationDeDate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocationDeFilm`.`ConservationDeDate` (
  `codeconsevationdedate` INT NOT NULL AUTO_INCREMENT,
  `DateDeLocation` DATETIME NOT NULL,
  `DateDeModification` DATETIME NOT NULL,
  `FilmsLoues_CodeLocation` INT NOT NULL,
  PRIMARY KEY (`codeconsevationdedate`, `FilmsLoues_CodeLocation`),
  INDEX `fk_ConservationDeDate_FilmsLoues1_idx` (`FilmsLoues_CodeLocation` ASC) VISIBLE,
  CONSTRAINT `fk_ConservationDeDate_FilmsLoues1`
    FOREIGN KEY (`FilmsLoues_CodeLocation`)
    REFERENCES `LocationDeFilm`.`FilmsLoues` (`CodeLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LocationDeFilm`.`Paiements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LocationDeFilm`.`Paiements` (
  `CodePaiements` INT NOT NULL AUTO_INCREMENT,
  `DateDePaiement` DATETIME NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Montant` DECIMAL(10,0) NOT NULL,
  `FilmsLoues_CodeLocation` INT NOT NULL,
  PRIMARY KEY (`CodePaiements`, `FilmsLoues_CodeLocation`),
  INDEX `fk_Paiements_FilmsLoues1_idx` (`FilmsLoues_CodeLocation` ASC) VISIBLE,
  CONSTRAINT `fk_Paiements_FilmsLoues1`
    FOREIGN KEY (`FilmsLoues_CodeLocation`)
    REFERENCES `LocationDeFilm`.`FilmsLoues` (`CodeLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
